-- MySQL Script generated by MySQL Workbench
-- Fri Apr 26 17:48:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Table `my_board`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_board`.`board` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
  `board_name` VARCHAR(100) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_board`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_board`.`post` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `board_id` BIGINT NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `password` INT(4) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` TEXT NULL,
  `posted_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_board`.`reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_board`.`reply` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` BIGINT NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `password` INT(4) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `replied_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
